#!/bin/sh
PATH=/usr/bin:/bin:/usr/sbin:/sbin
BRIDGE_HOST=${BRIDGE_HOST:-127.0.0.1}
BRIDGE_PORT=${BRIDGE_PORT:-8189}
BRIDGE_LOG=${BRIDGE_LOG:-/tmp/d810-bridge-v21.log}
NC_BIN=${NC_BIN:-/usr/bin/nc}

status_trace_log() {
  [ "${D810D_TRACE_STATUS:-0}" = "1" ] || return 0
  printf '[status-v21][%s] %s\n' "$(date +%s)" "$1" >> "$BRIDGE_LOG"
}

status_trace_log "received query=${QUERY_STRING:-}"
status_trace_log "headers trace=${HTTP_X_D810_TRACE:-} event=${HTTP_X_D810_EVENT:-} client=${HTTP_X_D810_CLIENT:-} ui_at=${HTTP_X_D810_UI_AT:-} ui_stage=${HTTP_X_D810_UI_STAGE:-} ui_action=${HTTP_X_D810_UI_ACTION:-}"

OUT=$(printf '%s\n' STATUS | "$NC_BIN" "$BRIDGE_HOST" "$BRIDGE_PORT" 2>>"$BRIDGE_LOG")
status_trace_log "bridge response ${OUT%%$'\n'*}"
if [ -z "$OUT" ]; then
  OUT='{"ok":false,"status":"bridge_unavailable","cameraDetected":false,"liveView":false}'
fi

printf 'Content-Type: application/json\r\nCache-Control: no-store\r\n\r\n'
printf '%s\n' "$OUT"
