#!/bin/sh /etc/rc.common

START=95
USE_PROCD=1

PROG=/overlay/usr/sbin/tailscaled
STATE=/overlay/etc/tailscale/tailscaled.state
SOCKET=/tmp/tailscaled.sock

start_service() {
    procd_open_instance
    procd_set_param command "$PROG" \
        --no-logs-no-support \
        --state="$STATE" \
        --socket="$SOCKET"
    procd_set_param env GOMEMLIMIT=32MiB
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
