$ErrorActionPreference = 'Stop'

$remoteUiRoot = Join-Path $PSScriptRoot '..\..\app\remote-ui'
$bridge = Get-Content -LiteralPath (Join-Path $remoteUiRoot 'cgi-bin\d810bridge.lua') -Raw -Encoding utf8
$legacyBridge = Get-Content -LiteralPath (Join-Path $remoteUiRoot 'cgi-bin\d810d.lua') -Raw -Encoding utf8
$action = Get-Content -LiteralPath (Join-Path $remoteUiRoot 'cgi-bin\action-v21') -Raw -Encoding utf8
$sessionManager = Get-Content -LiteralPath (Join-Path $remoteUiRoot 'cgi-bin\session-manager') -Raw -Encoding utf8
$capturedPreview = Get-Content -LiteralPath (Join-Path $remoteUiRoot 'cgi-bin\captured-preview') -Raw -Encoding utf8
$capturedObject = Get-Content -LiteralPath (Join-Path $remoteUiRoot 'cgi-bin\captured-object') -Raw -Encoding utf8
$capturedImages = Get-Content -LiteralPath (Join-Path $remoteUiRoot 'cgi-bin\captured-images') -Raw -Encoding utf8
$capturedThumbnail = Get-Content -LiteralPath (Join-Path $remoteUiRoot 'cgi-bin\captured-thumbnail') -Raw -Encoding utf8
$capturedNef = Get-Content -LiteralPath (Join-Path $remoteUiRoot 'cgi-bin\captured-nef') -Raw -Encoding utf8
$ui = Get-Content -LiteralPath (Join-Path $remoteUiRoot '0716-1.1.html') -Raw -Encoding utf8
$uiPortraitAlias = Get-Content -LiteralPath (Join-Path $remoteUiRoot '0716-1.html') -Raw -Encoding utf8
$uiLandscapeAlias = Get-Content -LiteralPath (Join-Path $remoteUiRoot '0716-landscape.html') -Raw -Encoding utf8
$variantEnv = Get-Content -LiteralPath (Join-Path $remoteUiRoot 'cgi-bin\variant-v21-env.sh') -Raw -Encoding utf8
$bridgeCommon = Get-Content -LiteralPath (Join-Path $remoteUiRoot 'cgi-bin\bridge-common.sh') -Raw -Encoding utf8
$websocket = Get-Content -LiteralPath (Join-Path $remoteUiRoot 'cgi-bin\d810ws.lua') -Raw -Encoding utf8
$status = Get-Content -LiteralPath (Join-Path $remoteUiRoot 'cgi-bin\status-v21') -Raw -Encoding utf8
$liveview = Get-Content -LiteralPath (Join-Path $remoteUiRoot 'cgi-bin\liveview-v21') -Raw -Encoding utf8
$runtimeGuardian = Get-Content -LiteralPath (Join-Path $remoteUiRoot 'cgi-bin\runtime-guardian') -Raw -Encoding utf8
$batteryWorker = Get-Content -LiteralPath (Join-Path $remoteUiRoot 'cgi-bin\battery-worker') -Raw -Encoding utf8
$captureEvent = Get-Content -LiteralPath (Join-Path $remoteUiRoot 'cgi-bin\capture-event') -Raw -Encoding utf8
$repoRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$ddserver = Get-Content -LiteralPath (Join-Path $repoRoot '_tmp_ddserver\src\communicator.cpp') -Raw -Encoding utf8
$androidLiveView = Get-Content -LiteralPath (Join-Path $repoRoot 'app\flutter_camera\android\app\src\main\kotlin\com\example\underlab_camera\MainActivity.kt') -Raw -Encoding utf8
$flutterMain = Get-Content -LiteralPath (Join-Path $repoRoot 'app\flutter_camera\lib\main.dart') -Raw -Encoding utf8
$flutterCameraApi = Get-Content -LiteralPath (Join-Path $repoRoot 'app\flutter_camera\lib\camera_api.dart') -Raw -Encoding utf8
$ddserverStage = Get-Content -LiteralPath (Join-Path $repoRoot 'deploy\scripts\stage-ddserver-openwrt.ps1') -Raw -Encoding utf8
$ddserverInit = Get-Content -LiteralPath (Join-Path $repoRoot 'deploy\openwrt\ddserver\files\ddserver.init') -Raw -Encoding utf8

function Assert-Contains([string]$text, [string]$pattern, [string]$message) {
  if ($text -notmatch [regex]::Escape($pattern)) {
    throw "FAIL: $message"
  }
  Write-Output "PASS: $message"
}

function Assert-NotContains([string]$text, [string]$pattern, [string]$message) {
  if ($text -match [regex]::Escape($pattern)) {
    throw "FAIL: $message"
  }
  Write-Output "PASS: $message"
}

Assert-Contains $bridge 'function BridgeSession:restore_live_view_after_connect()' 'session recovery has a live-view restore path'
Assert-Contains $bridge 'probe_camera_state({ includeHardware = false, force = true })' 'idle status verifies the live PTP session instead of trusting cached ready state'
Assert-Contains $bridge 'status returning degraded' 'failed PTP probes are reported as degraded rather than idle or ready'
Assert-Contains $bridge 'camera_stop_confirmed and self.transport_ready and "ready" or "degraded"' 'LIVE stop cannot overwrite a broken transport with ready'
Assert-Contains $bridge 'self.transport_ready = false' 'failed LIVE startup clears stale transport readiness'
Assert-Contains $legacyBridge 'camera PTP status probe failed' 'legacy status requires a successful PTP property probe'
Assert-Contains $bridge 'self.live_session_id, self.live_session_label = ensure_live_session()' 'live session identity is restored from the existing session'
Assert-Contains $bridge 'function BridgeSession:af()' 'bridge exposes AF as an independent action'
Assert-Contains $bridge 'camera remained busy after AF' 'AF waits until Nikon releases DeviceBusy before returning'
Assert-Contains $bridge 'fail("camera_busy", string.format("camera busy while setting prop' 'PTP DeviceBusy is not misreported as camera missing'
Assert-Contains $bridge 'function BridgeSession:shutter()' 'bridge exposes SHOT as an independent action'
Assert-Contains $bridge 'function rethrow(err, fallback_status)' 'nested camera failures preserve their structured Nikon error'
Assert-Contains $bridge 'Recording-media' 'idle slider prepare documents the Live View-only recording-media property'
Assert-Contains $bridge 'rethrow(prepare_err)' 'slider prepare returns the original camera failure'
Assert-Contains $bridge 'shutter reconciled stale live-view state from camera' 'single shutter checks the physical Nikon live-view state before PC-mode capture'
Assert-Contains $bridge 'function DdServerWire:get_events()' 'bridge reads the Nikon event queue'
Assert-Contains $bridge 'OBJECT_ADDED = 0x4002' 'bridge recognizes PTP ObjectAdded events'
Assert-Contains $bridge 'function BridgeSession:capture_events()' 'bridge converts camera events into capture state'
Assert-Contains $captureEvent 'CAPTURE_EVENTS' 'capture event endpoint requests camera events without a preview image'
Assert-Contains $bridge 'self:execute(NIKON_CHANGE_CAMERA_MODE, { 1 })' 'program shutter enters Nikon PC control mode'
Assert-Contains $bridge 'function DdServerWire:release_camera_control()' 'program shutter can return camera controls to the body'
Assert-Contains $bridge 'if mode_response == NIKON_INVALID_STATUS then' 'successful D810 capture is not reversed by idempotent 0xA003 release'
Assert-Contains $bridge 'self:release_camera_control()' 'program shutter releases camera controls after capture'
Assert-Contains $bridge 'function BridgeSession:raw_mode()' 'bridge exposes RAW mode as an independent action'
Assert-Contains $bridge 'PROP_COMPRESSION_SETTING, string.char(COMPRESSION_RAW_WITH_FINE_JPEG)' 'RAW mode explicitly sets Nikon compression to RAW plus Fine JPEG'
Assert-Contains $bridge 'local data_container = pack_container(CONTAINER_DATA, code, payload):sub(5)' 'property writes use a separate PTP data container'
Assert-Contains $bridge 'le_u32(4 + #command_container + #data_container)' 'ddserver receives command and data in one framed packet'
Assert-Contains $bridge 'acquire_lock(COMMAND_ACTION_LOCK, COMMAND_LOCK_TIMEOUT_MS)' 'camera actions share the command lock'
Assert-Contains $action 'recover)' 'action endpoint exposes session recovery'
Assert-Contains $action 'OUT=$(action_bridge_request RECOVER)' 'session recovery forwards to the existing bridge session'
Assert-Contains $bridgeCommon 'BRIDGE_ACTION_DECLARED_HEALTHY=1' 'action guard exposes a verified fresh healthy declaration'
Assert-Contains $action 'healthy_recover_response()' 'healthy recovery has a queue-free declaration response'
Assert-Contains $action 'true:live:0) [ -f "$SESSION_LIVE_REQUEST" ] || return 1' 'live healthy no-op requires matching explicit live intent'
Assert-Contains $action 'false:ready:0) [ ! -f "$SESSION_LIVE_REQUEST" ] || return 1' 'idle healthy no-op cannot override explicit live intent'
Assert-Contains $action 'healthy declaration matches live intent; skipping RECOVER' 'matching healthy recovery never enters the camera command queue'
Assert-Contains $action 'OUT=$(action_bridge_request RAW_MODE)' 'RAW action forwards to the existing bridge session'
Assert-Contains $action 'OUT=$(action_bridge_request UNLOCK)' 'unlock action returns control to the camera body'
Assert-Contains $action 'action_trace_log "received query=' 'action ingress writes correlated stage telemetry'
Assert-NotContains $action 'field_event_log action_received' 'action ingress avoids a duplicate synchronous field event'
Assert-Contains $action 'action_result_log PASS' 'action completion writes a correlated result'
Assert-Contains $action 'COMMAND_ID=$(telemetry_token' 'client command identity is sanitized before logging'
Assert-Contains $bridgeCommon 'D810D_CLOCK_BASE_MS=' 'shell telemetry initializes its precise clock once per process'
Assert-Contains $bridgeCommon 'current_uptime_ms=$(uptime_ms)' 'subsequent shell timestamps avoid spawning Lua'
Assert-Contains $flutterCameraApi "'X-D810-Trace': traceId" 'S10 actions send the operation trace id'
Assert-Contains $flutterCameraApi "'X-D810-Command-Id': commandId" 'S10 actions send a unique command id'
Assert-Contains $flutterCameraApi 'field-events.jsonl' 'S10 keeps a persistent field telemetry file'
Assert-Contains $flutterCameraApi 'flush: true' 'S10 flushes each completed request to app storage'
Assert-Contains $flutterCameraApi '_telemetryRotateBytes' 'S10 persistent telemetry has bounded rotation'
Assert-Contains $action 'restoring live session after recovery' 'action endpoint restores live mode after recovery'
Assert-Contains $action 'if [ -f "$SESSION_LIVE_REQUEST" ]; then' 'recovery restores live view only from explicit client intent'
Assert-NotContains $action '[ -f "$SESSION_LIVE_REQUEST" ] || [ -f "${D810D_LIVE_SESSION_PATH' 'stale live-session metadata cannot resurrect live view'
Assert-Contains $action 'bridge_action_guard' 'camera actions trigger the runtime guard'
Assert-Contains $action 'acquire_live_action_lock' 'server serializes live intent and bridge transitions'
Assert-Contains $action 'stop_legacy_frame_refresh_if_present()' 'action endpoint centralizes legacy frame worker cleanup'
Assert-Contains $action '[ -r "$refresh_pidfile" ] || [ -d "$refresh_lockdir" ] || return 0' 'healthy action path skips legacy worker process cleanup when no worker state exists'
Assert-NotContains $action '/bin/sh "$SCRIPT_DIR/frame-refresh-v21" stop >/dev/null 2>&1 || true`r`n    action_trace_log' 'live actions do not unconditionally launch legacy worker cleanup'
Assert-Contains $status 'OUT=$(printf ''%s\n'' STATUS | "$NC_BIN" "$BRIDGE_HOST" "$BRIDGE_PORT"' 'status reads the current snapshot over one direct bridge connection'
Assert-NotContains $status 'bridge-common.sh' 'status does not load the process-heavy runtime management library'
Assert-Contains $runtimeGuardian 'RUNTIME_GUARDIAN_INTERVAL:-30' 'runtime guardian is a low-frequency safety net'
Assert-Contains $runtimeGuardian 'session_health_start' 'runtime guardian recovers the session health worker'
Assert-Contains $runtimeGuardian '[ "$owner" = "$$" ]' 'runtime guardian only removes its own pid file'
Assert-Contains $runtimeGuardian "trap 'exit 0' INT TERM HUP" 'runtime guardian exits when it receives a stop signal'
Assert-NotContains $runtimeGuardian '[ -f "$SESSION_LIVE_REQUEST" ] || [ -f "${D810D_LIVE_SESSION_PATH' 'guardian never restores live view from stale session metadata'
Assert-Contains $batteryWorker 'BATTERY_POLL_SEC:-30' 'battery worker wakes at a low frequency'
Assert-Contains $batteryWorker 'BATTERY_REFRESH_SEC:-600' 'battery value is refreshed at ten-minute intervals'
Assert-Contains $sessionManager 'HARD_RESET_REQUEST" -eq 0' 'new browser sessions do not inherit the previous live session'
Assert-Contains $sessionManager '&& [ -f "$SESSION_LIVE_REQUEST" ]; then' 'session restart preserves live view only while explicit intent exists'
Assert-Contains $sessionManager 'new browser session requested; clearing prior live session' 'new browser sessions clear live-session state'
Assert-Contains $sessionManager 'purge_runtime_tmp' 'new browser sessions clear runtime caches'
Assert-Contains $sessionManager 'D810D_GLOBAL_LOG:-/root/d810-camera-events.log' 'session manager has a persistent camera log'
Assert-Contains $sessionManager 'D810D_SESSION_LOG_MAX_KIB:-10240' 'session logs have a 10MiB retention cap'
Assert-Contains $sessionManager 'prune_session_logs' 'oldest session logs are pruned at session startup'
Assert-Contains $sessionManager 'SESSION_STAGE_MAX_ATTEMPTS=${D810D_SESSION_STAGE_MAX_ATTEMPTS:-40}' 'serialized startup allows generous stage retries'
Assert-Contains $sessionManager 'SESSION_STAGE_ATTEMPT_TIMEOUT=${D810D_SESSION_STAGE_ATTEMPT_TIMEOUT:-30}' 'each stage attempt has only a hung-request watchdog'
Assert-Contains $sessionManager 'stage=ptp_boot failed attempt=$attempt; restarting bridge stage only' 'PTP boot retries only the failed bridge stage'
Assert-Contains $sessionManager 'start_workers_serial()' 'workers start behind serialized stage barriers'
Assert-Contains $sessionManager 'retrying this stage only' 'worker failures do not rewind completed stages'
Assert-Contains $sessionManager 'returning failure without degraded success' 'exhausted startup does not report false success'
Assert-Contains $bridgeCommon 'GLOBAL_CAMERA_LOG=${D810D_GLOBAL_LOG:-/root/d810-camera-events.log}' 'shell bridge events use a persistent camera log'
Assert-Contains $bridgeCommon 'bridge_request_timed()' 'bridge shell supports bounded control requests'
Assert-Contains $bridge 'state = healthy and "healthy" or "unhealthy"' 'bridge publishes its own health declaration'
Assert-Contains $bridge 'expiresAtSec = tostring' 'bridge health declarations expire when the producer stops'
Assert-Contains $bridgeCommon 'bridge_declares_healthy()' 'normal actions use the bridge health declaration'
Assert-Contains $bridgeCommon 'invoking guardian' 'heavy runtime inspection is reserved for abnormal health'
Assert-Contains $liveview 'if [ -z "$SERVE_FRAME" ]; then' 'cached frames invoke the runtime guardian only when unavailable'
Assert-Contains $bridge 'GLOBAL_LOG_ROTATE_BYTES' 'bridge persistent log has a bounded rotation threshold'
Assert-Contains $bridge 'D810D_SESSION_LOG_ROTATE_BYTES' 'active session log has a bounded rotation threshold'
Assert-Contains $bridge 'D810D_TRACE_TRANSPORT' 'verbose transport reads are opt-in so useful history survives rotation'
Assert-Contains $bridge 'length > MAX_TRANSPORT_PACKET_BYTES' 'bridge rejects corrupt packet lengths before a huge socket read'
Assert-Contains $bridgeCommon 'BRIDGE_DAEMON_LOG=${D810D_BRIDGE_DAEMON_LOG:-/dev/null}' 'bridge stderr cannot duplicate the persistent session log'
Assert-Contains $websocket 'GLOBAL_LOG_ROTATE_BYTES' 'websocket persistent log has a bounded rotation threshold'
Assert-Contains $bridge 'stream_broadcast(stream_clients, frame, meta)' 'bridge publishes each captured frame to the direct stream'
Assert-Contains $bridge 'LIVE_FRAME_CACHE_INTERVAL_MS' 'direct live view rate-limits the fallback frame cache'
Assert-Contains $bridge 'D810D_LIVE_FRAME_CACHE_INTERVAL_MS") or "1000"' 'direct live view uses a one-second fallback cache'
Assert-Contains $bridge 'writeLastGood = write_last_good' 'last-good cache updates at a lower frequency'
Assert-Contains $bridge 'function BridgeSession:live_frame_failure_backoff_ms()' 'failed frame capture has bounded backoff'
Assert-Contains $bridge 'live_start first frame verification failed' 'LIVE is not reported ready until a fresh camera frame succeeds'
Assert-Contains $bridge 'self:_capture_frame(false, false, true)' 'LIVE readiness cannot be satisfied by a stale cached frame'
Assert-Contains $bridge 'self:execute(0x1003)' 'bridge shutdown releases the camera-side PTP session'
Assert-Contains $bridge 'local connect_blocks = self:read_response_blocks(1)' 'device connect is acknowledged before PTP session open'
Assert-Contains $bridge 'sleep_ms(150)' 'USB reconnect has a bounded settle interval before OpenSession'
Assert-Contains $bridge 'live_start first frame pending attempt=' 'first-frame warmup retries do not restart Nikon LIVE'
Assert-Contains $bridge 'live restore first frame verification failed' 'recovered LIVE also requires a fresh first frame'
Assert-Contains $bridge 'self.live_view_active = probe.liveView == true' 'camera probe, not stale client intent, controls actual LIVE state'
Assert-Contains $bridge 'transport_ready = false' 'failed camera probes cannot advertise a ready transport'
Assert-Contains $bridge 'elseif live_capture_failed then' 'failed frame backoff runs after command polling'
Assert-Contains $bridge 'if type(err) == "table" then' 'live transport preserves structured errors for recovery'
Assert-Contains $bridge 'function BridgeSession:recover_transport(reason, preserve_live_intent)' 'background live frames reconnect after ddserver loss'
Assert-Contains $bridge 'recover endpoint skipped: transport already healthy' 'client recovery requests do not reconnect a healthy PTP session'
Assert-Contains $bridge 'frame_age_ms <= 3000' 'healthy live recovery requires a recent successful frame'
Assert-Contains $bridge 'force = true' 'idle recovery verifies the camera transport before becoming a no-op'
Assert-Contains $bridge 'self:recover_transport("background live frame transport failure", true)' 'ddserver recovery preserves explicit live intent across procd delay'
Assert-Contains $bridge 'self:connect(not requested_live)' 'live recovery refuses sticky process fallback during ddserver respawn'
Assert-Contains $bridge 'local allow_legacy_fallback = not (self.session_mode_live == true or self.live_view_active == true)' 'all automatic reconnects preserve persistent live transport'
Assert-Contains $bridge 'self:recover_transport("ensure transport during live view", true)' 'live ensure-connected failures restore producer intent'
Assert-Contains $bridge 'error_status == "transport_error" or error_status == "liveview_start_failed"' 'failed live restart remains eligible for persistent transport recovery'
Assert-Contains $bridge 'self:save_session_mode("live")' 'failed live transport recovery remains eligible for bounded retry'
Assert-Contains $bridge 'cameraStopConfirmed = camera_stop_confirmed' 'STOP reports camera confirmation while always fencing the local producer'
Assert-Contains $bridge 'self:recover_transport("live stop transport failure")' 'STOP retries once through a fresh ddserver transport'
Assert-Contains $bridge 'clients[i]:write(prefix)' 'direct stream writes the small frame prefix separately'
Assert-Contains $bridge 'clients[i]:write(frame)' 'direct stream avoids joining the JPEG into a packet string'
Assert-Contains $bridge 'elseif not (session.live_view_active and session.session_mode_live == true and #stream_clients > 0) then' 'active direct streaming skips the idle loop sleep'
Assert-Contains $websocket 'local direct_stream = connect_direct_stream()' 'websocket prefers the direct bridge stream'
Assert-Contains $bridge 'function DdServerWire:execute_live_view_image(wait_hook)' 'bridge has a dedicated 0x9203 response parser'
Assert-Contains $bridge 'self:prime_live_view_state()' 'Nikon live start primes camera state before StartLiveView'
Assert-Contains $bridge 'D810D_ENABLE_CAPTURE_IN_SDRAM") ~= "0"' 'Nikon live start selects SDRAM recording by default'
Assert-Contains $bridge 'response_code == 0xA004' 'Nikon InvalidStatus is re-primed and retried'
Assert-Contains $bridge 'LIVE_VIEW_START_RETRY_COUNT' 'Nikon transient busy is bounded during live start'
Assert-Contains $bridge 'camera live start did not settle' 'Nikon asynchronous live start has a bounded settle phase'
Assert-Contains $bridge 'burst shutter accepted asynchronously' 'Nikon asynchronous burst completion is not retransmitted'
Assert-Contains $bridge 'self.legacy_transport_only = false' 'successful persistent reconnect exits process-based fallback'
Assert-Contains $bridge 'return "D8L5"' 'bridge emits compact binary live metadata'
Assert-Contains $websocket 'using frame-file fallback' 'websocket retains the frame-file fallback'
Assert-Contains $websocket 'local meta_raw, meta_err = read_exact(stream, meta_length)' 'websocket reads direct metadata without splitting a combined payload'
Assert-Contains $websocket 'return frame, nil, frame_id, meta_raw' 'websocket forwards bridge metadata without JSON re-encoding'
Assert-Contains $websocket 'send_ws_frame(sock, 0x2, meta_payload)' 'websocket sends direct metadata as binary'
Assert-Contains $websocket 'send_ws_frame(sock, 0x2, frame)' 'websocket sends its frame header separately from the JPEG'
Assert-Contains $websocket 'local ok_fork, pid = pcall(nixio.fork)' 'websocket accepts clients in isolated workers'
Assert-Contains $websocket 'MAX_WS_CLIENTS' 'websocket bounds concurrent client workers'
Assert-Contains $websocket 'pcall(nixio.waitpid, pid, "nohang")' 'websocket reaps completed client workers'
Assert-Contains $websocket 'if not wait_for_live_request(sock) then' 'websocket idles stale reconnects while live view is stopped'
Assert-Contains $websocket 'send_ws_frame(sock, 0x9, "")' 'idle websocket workers detect disconnected clients'
Assert-Contains $websocket 'live intent cleared; closing websocket worker' 'STOP terminates direct-stream websocket workers before fallback'
Assert-Contains $websocket 'live intent cleared during fallback; closing websocket worker' 'STOP terminates fallback websocket workers'
Assert-Contains $ui 'function parseLiveBinaryMeta(data)' 'UI parses compact binary live metadata'
Assert-Contains $ui 'websocket-direct-binary' 'UI identifies the optimized direct stream'
Assert-Contains $ddserver 'DDSERVER_BULK_READ_SIZE' 'ddserver exposes configurable USB bulk reads'
Assert-Contains $ddserver 'mUsbReadBuffer.resize' 'ddserver reuses its USB frame buffer'
Assert-Contains $ddserver 'ptpPacket = (PtpPacket *)&buf[4];' 'ddserver refreshes packet pointers after USB buffer growth'
Assert-Contains $ddserver 'packetSize1 = le32toh(ptpPacket->packet_len);' 'ddserver decodes USB packet lengths explicitly'
Assert-Contains $ddserver 'MAX_PACKET_SIZE' 'ddserver rejects implausible camera packet lengths'
Assert-Contains $ddserver 'liveview9203 bulk_size=' 'ddserver can trace 0x9203 USB timing'
Assert-NotContains $ddserverStage "_tmp_ddserver\files" 'ddserver staging preserves the authoritative procd init files'
Assert-Contains $ddserverInit 'procd_set_param respawn 3600 5 -1' 'ddserver cannot exhaust a finite crash retry budget'
Assert-Contains $capturedPreview '. "$SCRIPT_DIR/variant-v21-env.sh"' 'captured JPEG preview uses the v21 runtime environment'
Assert-Contains $capturedObject 'CAPTURED_OBJECT_JPEG' 'full-size JPEG endpoint streams the captured object'
Assert-Contains $capturedObject 'CAPTURED_OBJECT_JPEG $HANDLE' 'full-size JPEG endpoint selects a requested SD-card image handle'
Assert-Contains $capturedImages 'CAPTURED_IMAGES $LIMIT' 'captured image browser requests a bounded SD-card JPEG list'
Assert-Contains $capturedThumbnail 'CAPTURED_THUMB %s' 'captured image browser streams a selected thumbnail'
Assert-Contains $bridge 'function BridgeSession:list_recent_jpeg_objects' 'bridge lists recent JPEG metadata without retaining image blobs'
Assert-Contains $bridge 'CAPTURED_BROWSER_LIST_LIMIT = tonumber(os.getenv("D810D_CAPTURED_BROWSER_LIST_LIMIT") or "1000")' 'image browser supports the full field-session JPEG handle range'
Assert-Contains $bridge 'GetObjectInfo transaction per photo while live view is running' 'image browser avoids per-photo metadata scans while live view is running'
Assert-Contains $bridge 'function BridgeSession:captured_thumbnail_stream' 'bridge streams thumbnails by object handle'
Assert-Contains $capturedObject 'LOCK_PATH=${D810D_CAPTURED_OBJECT_LOCK:-/tmp/d810-captured-object-download.lock}' 'full-size JPEG endpoint serializes object downloads'
Assert-Contains $capturedObject 'dd bs=65536' 'full-size JPEG endpoint forwards the binary stream without buffering it'
Assert-Contains $capturedNef 'CAPTURED_OBJECT_NEF' 'NEF endpoint requests the latest raw object'
Assert-Contains $capturedNef 'dd bs=65536' 'NEF endpoint forwards the raw stream without buffering it'
Assert-Contains $bridge 'function BridgeSession:select_latest_nef_object()' 'bridge can select a recent NEF object'
Assert-Contains $bridge 'session:captured_object_stream(conn, "nef")' 'bridge reuses chunk streaming for NEF delivery'
Assert-Contains $bridge 'self:_wire():stop_live_view()' 'full-size JPEG pauses live view during object transfer'
Assert-Contains $bridge 'self:_wire():start_live_view()' 'full-size JPEG restores live view after object transfer'
Assert-Contains $bridge 'object_wire.timeout = CAPTURED_OBJECT_TIMEOUT' 'full-size JPEG uses an object-transfer timeout'
Assert-Contains $bridge 'captured object size mismatch' 'full-size JPEG validates the completed object size'
Assert-Contains $bridge 'CMD_GET_PARTIAL_OBJECT = 0x101B' 'full-size JPEG uses PTP partial-object transfer'
Assert-Contains $variantEnv 'D810D_CAPTURED_OBJECT_CHUNK_SIZE=4194304' 'full-size JPEG uses the measured 4MB transfer sweet spot'
Assert-Contains $variantEnv 'D810D_CAPTURED_OBJECT_SINGLE_CHUNK_LIMIT=4194304' 'small full-size JPEG uses one bounded transfer chunk'
Assert-Contains $variantEnv 'D810D_CAPTURED_OBJECT_LIVE_PAUSE_MS=150' 'full-size JPEG uses the measured live-view pause'
Assert-Contains $bridge 'return self.last_captured_object_info' 'full-size JPEG reuses the object selected by captured preview'
Assert-Contains $bridge 'effective_chunk_size = expected_size' 'small full-size JPEG is requested as one bounded chunk'
Assert-Contains $bridge 'delivery = "http_stream"' 'full-size JPEG is delivered without a tmp image file'
Assert-Contains $bridge 'conn:write(chunk)' 'full-size JPEG streams chunks directly to HTTP'
Assert-Contains $bridge 'pcall(function() conn:close() end)' 'full-size JPEG response closes before live-view restoration'
Assert-Contains $bridge 'wireMs = wire_ms' 'full-size JPEG measures PTP wire time separately'
Assert-Contains $bridge 'writeMs = socket_write_ms' 'full-size JPEG measures socket write time separately'
Assert-Contains $bridge 'chunkAvgMs = chunk_count > 0' 'full-size JPEG records per-chunk latency'
Assert-Contains $bridge 'captured object JPEG markers were invalid' 'full-size JPEG validates JPEG boundaries before publish'
Assert-Contains $ui 'capturedObject: "/cgi-bin/captured-object"' 'full-size viewer uses the captured object endpoint'
Assert-Contains $ui 'const keepLiveForCameraAction = ["af", "shutter"].includes(action);' 'UI keeps live view for AF and SHOT'
Assert-Contains $ui '!keepLiveForCameraAction && liveMode' 'UI does not stop live view before AF or SHOT'
Assert-Contains $ui 'async function recoverSession(reason = "runtime health check")' 'UI has an automatic recovery loop'
Assert-Contains $ui 'scheduleSessionRecovery("WebSocket disconnected", false)' 'WebSocket failures trigger recovery without refresh'
Assert-Contains $ui 'Fence client recovery before the server closes the stream' 'STOP disables client recovery before requesting server shutdown'
Assert-Contains $ui 'payload.liveView !== true && payload.status !== "liveview_on"' 'browser recovery honors a global server-side STOP'
Assert-Contains $uiPortraitAlias 'Fence reconnect/recovery before the server closes the stream' 'portrait alias fences recovery before STOP'
Assert-Contains $uiLandscapeAlias 'Fence reconnect/recovery before the server closes the stream' 'landscape alias fences recovery before STOP'
Assert-Contains $androidLiveView 'setTimeout(recoverAndReconnect, 500)' 'Android reconnect checks authoritative server intent'
Assert-Contains $androidLiveView 'fun reportFramePulse(value: String)' 'Android live view exposes a low-frequency frame ID pulse'
Assert-Contains $androidLiveView 'Log.i("EVF_PULSE", value.take(1000))' 'frame ID pulse is bounded before persistent diagnostic logging'
Assert-Contains $androidLiveView 'frameId: lastQueuedFrameId' 'frame pulse correlates displayed FPS with the latest received frame ID'
Assert-Contains $androidLiveView 'decodedQueue: decodedQueue.length' 'frame pulse identifies display queue pressure'
Assert-Contains $androidLiveView "payload.status === 'liveview_on'" 'Android reconnect resumes only while live view remains requested'
Assert-NotContains $androidLiveView 'startLiveAndConnect' 'opening Android live view never issues live-on'
Assert-NotContains $androidLiveView "action-v21?action=live-on" 'embedded Android WebView cannot start camera live view'
Assert-Contains $androidLiveView 'server is already live' 'Android WebView only attaches to an authoritative live session'
Assert-Contains $flutterMain 'bool cameraReady = false;' 'Flutter starts with camera state unknown instead of optimistic ready'
Assert-Contains $flutterMain 'bool liveView = false;' 'Flutter starts with live view disabled'
Assert-NotContains $flutterMain '_startInitialLiveView' 'Flutter startup cannot automatically request live view'
Assert-Contains $flutterMain '_cameraApi.runtimeStatus()' 'Flutter synchronizes authoritative runtime status'
Assert-Contains $flutterMain '_liveIntentGeneration' 'Flutter ignores stale live transition completions'
Assert-Contains $flutterMain '_runtimeStatusFailures >= 3' 'transient status loss does not tear down a healthy stream'
Assert-Contains $flutterMain 'Do not add a redundant hold-start HTTP round trip' 'slider release avoids a duplicate priority request'
Assert-Contains $flutterCameraApi 'class CameraRuntimeStatus' 'camera API models authoritative runtime state'
Assert-Contains $flutterCameraApi "'live-off' || 'reset' => _RequestPriority.emergency" 'STOP and RESET outrank queued camera work'
Assert-Contains $flutterMain 'for (final delay in const [0, 100, 180, 300, 480, 700])' 'Flutter probes the captured thumbnail immediately and tolerates SD-card commit variance'
Assert-Contains $flutterMain 'await precacheImage(provider, context);' 'Flutter decodes the full JPEG before swapping it into the animated viewer'
Assert-Contains $flutterCameraApi 'Future<List<CapturedImageEntry>> capturedImages' 'Flutter loads the bounded SD-card image list'
Assert-Contains $flutterMain 'void _previousImage()' 'Flutter image viewer navigates to older images'
Assert-Contains $flutterMain 'void _nextImage()' 'Flutter image viewer navigates to newer images'
Assert-Contains $flutterMain "label: const Text('9MP')" 'Flutter image viewer defers full JPEG transfer until requested'
Assert-Contains $ui 'scheduleSessionRecovery("live frame unavailable", false)' 'frame failures trigger recovery without refresh'
Assert-Contains $ui 'backendState === "degraded" || backendState === "recovering"' 'degraded backend status triggers recovery without refresh'
Assert-Contains $ui 'capturedPreview: "/cgi-bin/captured-preview"' 'shot preview uses the captured JPEG endpoint'
Assert-Contains $ui 'captureEvent: "/cgi-bin/capture-event"' 'external shutter detection uses the camera event endpoint'
Assert-Contains $ui 'const eventSeq = Number(payload.captureEventSeq);' 'external shutter detection compares event sequence numbers'
Assert-NotContains $ui '`${API.capturedPreview}?probe=' 'external shutter probe does not download the preview JPEG'
Assert-Contains $ui 'const MEASURE_END_TO_END_LATENCY = query.has("e2e");' 'UI can measure capture-to-image-load latency'
Assert-Contains $ui 'const MEASURE_TOTAL_LATENCY = query.get("e2e") === "total";' 'UI can measure PTP-start-to-image-load latency'
Assert-Contains $ui 'Date.now() - latencyStartedAt' 'end-to-end latency uses the selected pipeline timestamp'
Assert-Contains $ui 'class="shot-preview"' 'shot preview is rendered in the live-view corner'
Assert-Contains $ui 'async function requestPortraitViewer()' 'full-size shot viewer requests portrait mode'
Assert-Contains $ui 'screen.orientation.lock("portrait")' 'shot viewer requests a portrait orientation lock'
Assert-Contains $ui 'shotViewer.requestFullscreen' 'shot viewer requests full-screen presentation'
Assert-Contains $ui 'void requestPortraitViewer();' 'shot viewer requests full-screen immediately from the thumbnail tap'
Assert-Contains $ui 'shotViewerImage.src = shotThumbImage.src;' 'shot viewer displays the thumbnail immediately while the full JPEG loads'
Assert-Contains $ui 'shotViewerImage.src = `${API.capturedObject}?t=${Date.now()}`;' 'mobile viewer streams the full JPEG directly into the image element'
Assert-Contains $ui 'width: min(94vw, calc(94vh * 7360 / 4912));' 'portrait viewer gives the JPEG long edge three-percent side margins'
Assert-Contains $ui 'aspect-ratio: 7360 / 4912;' 'portrait viewer preserves the D810 JPEG aspect ratio'
Assert-Contains $ui 'shotViewerImage.addEventListener("click", () => void hideShotViewer());' 'tapping the full-size JPEG returns to live view'
Assert-Contains $ui 'const retryDelays = [0, 450, 900, 1800, 3000];' 'shot preview retries while the camera finishes saving'

Write-Output 'PASS: live-view AF/shutter contract checks completed'
